-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS tasks CASCADE;

DROP TABLE IF EXISTS classes CASCADE;

DROP TABLE IF EXISTS taskclasses CASCADE;